### ISSUE TITLE
aws region is tied to ami-id in example cfg file

### ISSUE THREAD

**Issue by tijko** [tbenthompson/anti_forgetful#3]
Running the example configuration file while having a region other than `us-east-1` will return error on `ami-id` not found. 

```
Traceback (most recent call last):
  File "/home/tijko/anti_forgetful/virtual_anti_forgetful/bin/anti_forgetful", line 11, in <module>
    load_entry_point('anti-forgetful==18.4.24.4', 'console_scripts', 'anti_forgetful')()
  File "/home/tijko/anti_forgetful/virtual_anti_forgetful/lib/python3.6/site-packages/anti_forgetful-18.4.24.4-py3.6.egg/anti_forgetful/launch.py", line 10, in main
    instance_id = setup_instance(cfg)
  File "/home/tijko/anti_forgetful/virtual_anti_forgetful/lib/python3.6/site-packages/anti_forgetful-18.4.24.4-py3.6.egg/anti_forgetful/launch.py", line 33, in setup_instance
    with SessionInstance(cfg, image_id = cfg.base_image_id) as s:
  File "/home/tijko/anti_forgetful/virtual_anti_forgetful/lib/python3.6/site-packages/anti_forgetful-18.4.24.4-py3.6.egg/anti_forgetful/instance.py", line 15, in __enter__
    self.create_instance()
  File "/home/tijko/anti_forgetful/virtual_anti_forgetful/lib/python3.6/site-packages/anti_forgetful-18.4.24.4-py3.6.egg/anti_forgetful/instance.py", line 49, in create_instance
    'Tags': [{'Key': 'Name', 'Value': self.cfg.instance_name}]
  File "/home/tijko/anti_forgetful/virtual_anti_forgetful/lib/python3.6/site-packages/boto3-1.7.14-py3.6.egg/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/tijko/anti_forgetful/virtual_anti_forgetful/lib/python3.6/site-packages/boto3-1.7.14-py3.6.egg/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/tijko/anti_forgetful/virtual_anti_forgetful/lib/python3.6/site-packages/botocore-1.10.14-py3.6.egg/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/tijko/anti_forgetful/virtual_anti_forgetful/lib/python3.6/site-packages/botocore-1.10.14-py3.6.egg/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-428aa838]' does not exist

```

I had to change my region from `us-east-2` to `us-east-1` with how the default setup in `example/awscfg.py` is configured.  

FWIW there's the api call for `describe_images` that would be able to provide an ami-id regardless of region.  

Or even back to #1 where I suggest having the region explicitly put in the awscfg.  By adding `us-east-1` and then passing to any `boto3` call that takes a region argument, this will effectively override any regions users might have in their `aws/config`.

**Comment by tbenthompson** [comment]
Thanks! Good suggestions. I'll work on this at some point soon.
